#pragma config(Sensor, in1,    ArmAngle,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  option,         sensorDigitalIn)
#pragma config(Motor,  port1,           LeftArm,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightRear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftWrist,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightWrist,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftArm2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightArm2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightArm,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


void setDrive(int leftPower, int rightPower){
	motor[LeftFront]=leftPower;
	motor[LeftRear]=leftPower;
	motor[RightFront]=rightPower;
	motor[RightRear]=rightPower;
}

void setArm(int power)
{
	motor[LeftArm]=power;
	motor[RightArm]=power;
	motor[LeftArm2]=power;
	motor[RightArm2]=power;
}

void setWrist(int power){
	motor[LeftWrist]=power;
	motor[RightWrist]=power;
}




void driveForT(int l, int r, int t){
	setDrive(l, r);
	wait1Msec(t);
	setDrive(0, 0);
}

void fwd(int t)
{
	driveForT(127, 127, t);
}

void bwd(int t)
{
	driveForT(-127, -127, t);
}

void Right(int t)
{
	driveForT(127, -127, t);
}

void Left(int t)
{
	driveForT(-127, 127, t);
}

void ArmUp(int t)
{
	setArm(127);
	wait1Msec(t);
	setArm(0);
}

int ArmAngleLimit = 0;

task ArmUpATask()
{
	setArm(127);
	while(SensorValue(ArmAngle)<ArmAngleLimit){}
	setArm(0);
}

void ArmUpAsync(int a){
	ArmAngleLimit = a;
	startTask(ArmUpATask);
}



void ArmDown(int t)
{
	setArm(-127);
	wait1Msec(t);
	setArm(0);
}

void WristDown(int t)
{
	setWrist(-127);
	wait1Msec(t);
	setWrist(0);
}


void Right_auto()
{
	ArmUpAsync(2200);
	fwd(1000);
	fwd(2134);
	bwd(400);
	Right(500);
	fwd(400);
	Left(500);
	fwd(500);
	bwd(400);
	Right(500);
	fwd(200);
	Left(600);
	fwd(500);
	bwd(500);
	Left(500);
	fwd(1400);
	Right(500);
	fwd(600);
	bwd(200);
	Left(500);
	fwd(500);
	Right(500);
	fwd(500);
	bwd(200);
	Left(500);
	fwd(500);
	Right(500);
	fwd(500);
}

void Left_auto()
{
	ArmUpAsync(2200);
	fwd(1000);
	fwd(2134);
	bwd(400);
	Left(500);
	fwd(400);
	Right(500);
	fwd(500);
	bwd(400);
	Left(500);
	fwd(200);
	Right(600);
	fwd(500);
	bwd(500);
	Right(500);
	fwd(1400);
	Left(500);
	fwd(600);
	bwd(200);
	Right(500);
	fwd(500);
	Left(500);
	fwd(500);
	bwd(200);
	Right(500);
	fwd(500);
	Left(500);
	fwd(500);
}

task autonomous()
{
	int isJumperSlotEmpty=SensorValue[option];
	if(isJumperSlotEmpty)// No Jumper
	{
		Left_auto();


  }
  else // Jumper In
  {
  	Right_auto();

	}


}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

 	while (true)
	{
    setDrive( vexRT[Ch3], vexRT[Ch2] );

		if(vexRT[Btn6U])
		{
			setArm(127);
		}
		else
		{
			if(vexRT[Btn6D])
			{
				setArm(-127);
			}
			else
			{
				setArm(0);
			}
		}

		if(vexRT[Btn5U])// lift
		{
			setWrist(127);
		}
		else
		{
			if(vexRT[Btn5D])
			{
				setWrist(-127);
			}
			else
			{
				setWrist(0);
			}
		}
	}
}
